/**
 * @fileoverview Query performance monitoring and optimisation service
 * @module database/services
 * @description Tracks every database query executed through the database
 * module, aggregates per-connection statistics, detects slow-query patterns,
 * and generates actionable optimisation suggestions for both SQL and MongoDB.
 *
 * Key capabilities:
 * - **Recording** — `recordQuery` stores execution metrics in a bounded history
 * - **Statistics** — per-connection totals, averages, slow/very-slow counts
 * - **Pattern analysis** — normalises queries into patterns and tracks their stats
 * - **Optimisation suggestions** — heuristic rules for missing indexes, `SELECT *`,
 *   leading-wildcard `LIKE`, sub-queries, `$regex`, large `$in`, etc.
 * - **Periodic analysis** — logs summaries and top-slow patterns every 60 s
 * - **Reporting** — `exportPerformanceReport` for dashboards or alerting
 *
 * @author Outhan Chazima
 * @version 1.0.0
 */

import { Injectable, Logger, OnModuleDestroy } from '@nestjs/common';
import { QueryPerformance } from '../interfaces/database.interface';
import { PERFORMANCE_THRESHOLDS } from '../database.constants';

/**
 * Aggregated statistics for a single database connection.
 *
 * @export
 * @interface QueryStatistics
 */
export interface QueryStatistics {
  /** Total number of recorded queries */
  totalQueries: number;
  /** Running average execution time in milliseconds */
  averageExecutionTime: number;
  /** Number of queries exceeding the slow threshold */
  slowQueries: number;
  /** Number of queries exceeding the very-slow threshold */
  verySlowQueries: number;
  /** Number of queries served from cache */
  cachedQueries: number;
  /** Number of queries that failed */
  failedQueries: number;
  /** Map of normalised query pattern → pattern-level statistics */
  queryPatterns: Map<string, QueryPatternStats>;
}

/**
 * Per-pattern execution statistics.
 *
 * @export
 * @interface QueryPatternStats
 */
export interface QueryPatternStats {
  /** Normalised query pattern string */
  pattern: string;
  /** Number of times this pattern was executed */
  count: number;
  /** Running average execution time in milliseconds */
  averageTime: number;
  /** Fastest recorded execution in milliseconds */
  minTime: number;
  /** Slowest recorded execution in milliseconds */
  maxTime: number;
  /** Timestamp of the most recent execution */
  lastExecuted: Date;
}

/**
 * A single optimisation suggestion generated by heuristic analysis.
 * @interface OptimizationSuggestion
 */
interface OptimizationSuggestion {
  /** Truncated query string (first 100 chars) */
  query: string;
  /** Description of the detected issue */
  issue: string;
  /** Recommended action to improve performance */
  suggestion: string;
  /** Estimated impact level */
  impact: 'low' | 'medium' | 'high';
}

/**
 * Service for monitoring, analysing, and optimising database query performance.
 *
 * @class QueryOptimizationService
 * @implements {OnModuleDestroy}
 * @description Collects query execution data, maintains per-connection
 * statistics and pattern histories, detects slow queries, and produces
 * optimisation suggestions based on heuristic rules.
 *
 * @example
 * ```typescript
 * optimizationService.enableMonitoring();
 * optimizationService.recordQuery({ query: 'SELECT ...', executionTime: 1200, ... });
 * const stats = optimizationService.getStatistics('main');
 * const suggestions = optimizationService.getOptimizationSuggestions('main');
 * ```
 */
@Injectable()
export class QueryOptimizationService implements OnModuleDestroy {
  /** Logger scoped to this service */
  private readonly logger = new Logger(QueryOptimizationService.name);

  /** Bounded FIFO history of all recorded queries */
  private readonly queryHistory: QueryPerformance[] = [];

  /** Map of connection name → aggregated statistics */
  private readonly statistics: Map<string, QueryStatistics> = new Map();

  /** Map of connection name → list of generated optimisation suggestions */
  private readonly optimizationSuggestions: Map<
    string,
    OptimizationSuggestion[]
  > = new Map();

  /** Whether periodic monitoring is currently active */
  private monitoringEnabled = false;

  /** Maximum number of entries kept in {@link queryHistory} */
  private readonly maxHistorySize = 10000;

  /** Handle for the periodic analysis interval (cleared on destroy) */
  private analysisIntervalRef: ReturnType<typeof setInterval> | null = null;

  /**
   * Enable periodic performance monitoring.
   *
   * Starts a 60-second interval that calls {@link analyzePerformance} to
   * log summaries and identify problematic patterns. Idempotent — calling
   * when already enabled is a no-op.
   */
  enableMonitoring(): void {
    if (this.monitoringEnabled) return;
    this.monitoringEnabled = true;
    this.logger.log('Query performance monitoring enabled');

    // Start periodic analysis
    this.analysisIntervalRef = setInterval(() => {
      this.analyzePerformance();
    }, 60000); // Analyze every minute
  }

  /**
   * Disable periodic performance monitoring and clear the interval.
   */
  disableMonitoring(): void {
    this.monitoringEnabled = false;
    if (this.analysisIntervalRef) {
      clearInterval(this.analysisIntervalRef);
      this.analysisIntervalRef = null;
    }
    this.logger.log('Query performance monitoring disabled');
  }

  /**
   * NestJS lifecycle hook — disables monitoring on module teardown.
   */
  onModuleDestroy(): void {
    this.disableMonitoring();
  }

  /**
   * Record a query execution and update statistics.
   *
   * If monitoring is disabled this method is a no-op. Otherwise the
   * performance entry is appended to history, per-connection statistics
   * are updated, slow queries trigger suggestion generation, and the
   * query pattern is analysed.
   *
   * @param performance - The query performance data to record.
   */
  recordQuery(performance: QueryPerformance): void {
    if (!this.monitoringEnabled) {
      return;
    }

    // Add to history
    this.queryHistory.push(performance);

    // Maintain history size
    if (this.queryHistory.length > this.maxHistorySize) {
      this.queryHistory.shift();
    }

    // Update statistics
    this.updateStatistics(performance);

    // Check for slow queries
    if (performance.slow) {
      this.handleSlowQuery(performance);
    }

    // Analyze query pattern
    this.analyzeQueryPattern(performance);
  }

  /**
   * Incrementally update per-connection statistics with a new query result.
   *
   * @param performance - The recorded query performance entry.
   */
  private updateStatistics(performance: QueryPerformance): void {
    const stats =
      this.statistics.get(performance.connection) ||
      this.createEmptyStatistics();

    stats.totalQueries++;

    if (performance.cached) {
      stats.cachedQueries++;
    }

    if (performance.executionTime > PERFORMANCE_THRESHOLDS.SLOW_QUERY_MS) {
      stats.slowQueries++;
    }

    if (performance.executionTime > PERFORMANCE_THRESHOLDS.VERY_SLOW_QUERY_MS) {
      stats.verySlowQueries++;
    }

    // Update average execution time
    stats.averageExecutionTime =
      (stats.averageExecutionTime * (stats.totalQueries - 1) +
        performance.executionTime) /
      stats.totalQueries;

    this.statistics.set(performance.connection, stats);
  }

  /**
   * Create a zeroed-out {@link QueryStatistics} instance.
   *
   * @returns Fresh statistics with all counters at zero.
   */
  private createEmptyStatistics(): QueryStatistics {
    return {
      totalQueries: 0,
      averageExecutionTime: 0,
      slowQueries: 0,
      verySlowQueries: 0,
      cachedQueries: 0,
      failedQueries: 0,
      queryPatterns: new Map(),
    };
  }

  /**
   * Handle a detected slow query.
   *
   * Logs a warning with truncated query details and generates
   * optimisation suggestions that are stored per-connection
   * (capped at the last 100 suggestions).
   *
   * @param performance - The slow query's performance data.
   */
  private handleSlowQuery(performance: QueryPerformance): void {
    this.logger.warn(
      `Slow query detected on ${performance.connection}: ${performance.executionTime}ms`,
      {
        query: performance.query.substring(0, 200),
        executionTime: performance.executionTime,
        rowsAffected: performance.rowsAffected,
      },
    );

    // Generate optimization suggestions
    const suggestions = this.generateOptimizationSuggestions(performance);

    if (suggestions.length > 0) {
      const existing =
        this.optimizationSuggestions.get(performance.connection) || [];
      this.optimizationSuggestions.set(
        performance.connection,
        [...existing, ...suggestions].slice(-100), // Keep last 100 suggestions
      );
    }
  }

  /**
   * Extract and update pattern-level statistics for a query.
   *
   * Normalises the query into a pattern (via {@link extractQueryPattern}),
   * then updates count, average, min, max, and last-executed timestamp.
   *
   * @param performance - The recorded query performance entry.
   * @returns Empty object (side-effect only).
   */
  private analyzeQueryPattern(
    performance: QueryPerformance,
  ): Record<string, unknown> {
    const stats = this.statistics.get(performance.connection);
    if (!stats) {
      return {};
    }

    // Extract query pattern (simplified)
    const pattern = this.extractQueryPattern(performance.query);

    const patternStats = stats.queryPatterns.get(pattern) || {
      pattern,
      count: 0,
      averageTime: 0,
      minTime: Infinity,
      maxTime: 0,
      lastExecuted: new Date(),
    };

    patternStats.count++;
    patternStats.averageTime =
      (patternStats.averageTime * (patternStats.count - 1) +
        performance.executionTime) /
      patternStats.count;
    patternStats.minTime = Math.min(
      patternStats.minTime,
      performance.executionTime,
    );
    patternStats.maxTime = Math.max(
      patternStats.maxTime,
      performance.executionTime,
    );
    patternStats.lastExecuted = performance.timestamp;

    stats.queryPatterns.set(pattern, patternStats);

    return {};
  }

  /**
   * Normalise a raw query string into a reusable pattern.
   *
   * - **SQL** — replaces string literals, numbers, and parameter
   *   placeholders (`$1`, `:param`) with `?`.
   * - **MongoDB JSON** — replaces values with their JavaScript types.
   * - Whitespace is collapsed and the result is capped at 200 chars.
   *
   * @param query - The raw query string.
   * @returns A normalised pattern string.
   */
  private extractQueryPattern(query: string): string {
    // Remove specific values to get the pattern
    let pattern = query;

    // For SQL queries
    if (
      query.includes('SELECT') ||
      query.includes('INSERT') ||
      query.includes('UPDATE') ||
      query.includes('DELETE')
    ) {
      // Remove string literals
      pattern = pattern.replace(/'[^']*'/g, '?');
      // Remove numeric literals
      pattern = pattern.replace(/\b\d+\b/g, '?');
      // Remove parameter placeholders
      pattern = pattern.replace(/\$\d+/g, '?');
      pattern = pattern.replace(/:\w+/g, '?');
    }
    // For MongoDB queries (JSON)
    else if (query.startsWith('{') || query.startsWith('[')) {
      try {
        const parsed = JSON.parse(query);
        pattern = this.extractMongoPattern(parsed);
      } catch {
        pattern = query.substring(0, 100);
      }
    }

    // Normalize whitespace
    pattern = pattern.replace(/\s+/g, ' ').trim();

    // Limit length
    return pattern.substring(0, 200);
  }

  /**
   * Recursively extract a structural pattern from a parsed MongoDB query.
   *
   * Replaces leaf values with their `typeof` string and arrays with
   * `[array]` to produce a shape-only representation.
   *
   * @param obj - A parsed JSON value from a MongoDB query.
   * @returns JSON string representing the structural pattern.
   */
  private extractMongoPattern(obj: unknown): string {
    if (typeof obj !== 'object' || obj === null) {
      return typeof obj;
    }

    if (Array.isArray(obj)) {
      return '[array]';
    }

    const analysis: Record<string, unknown> = {};
    const objRecord = obj as Record<string, unknown>;
    for (const key in objRecord) {
      if (typeof objRecord[key] === 'object' && objRecord[key] !== null) {
        analysis[key] = this.extractMongoPattern(objRecord[key]);
      } else {
        analysis[key] = typeof objRecord[key];
      }
    }

    return JSON.stringify(analysis);
  }

  /**
   * Generate heuristic optimisation suggestions for a query.
   *
   * Checks for common anti-patterns in both SQL and MongoDB queries:
   * - `SELECT` without `WHERE`/`LIMIT`
   * - `SELECT *`
   * - Slow `WHERE` clauses (possible missing index)
   * - Slow `JOIN` operations
   * - Sub-queries that could be JOINs
   * - Leading-wildcard `LIKE`
   * - Slow MongoDB queries / `$regex` / large `$in`
   * - Generally very slow or uncached queries
   *
   * @param performance - The query performance data.
   * @returns Array of generated suggestions (may be empty).
   */
  private generateOptimizationSuggestions(
    performance: QueryPerformance,
  ): OptimizationSuggestion[] {
    const suggestions: OptimizationSuggestion[] = [];
    const query = performance.query;

    // SQL-specific suggestions
    if (
      query.includes('SELECT') ||
      query.includes('UPDATE') ||
      query.includes('DELETE')
    ) {
      // Check for missing WHERE clause
      if (
        query.includes('SELECT') &&
        !query.includes('WHERE') &&
        !query.includes('LIMIT')
      ) {
        suggestions.push({
          query: query.substring(0, 100),
          issue: 'Query without WHERE or LIMIT clause',
          suggestion: 'Add WHERE clause or LIMIT to reduce result set',
          impact: 'high',
        });
      }

      // Check for SELECT *
      if (query.includes('SELECT *')) {
        suggestions.push({
          query: query.substring(0, 100),
          issue: 'Using SELECT * in query',
          suggestion: 'Specify only required columns to reduce data transfer',
          impact: 'medium',
        });
      }

      // Check for missing indexes (simplified check)
      if (query.includes('WHERE') && performance.executionTime > 1000) {
        suggestions.push({
          query: query.substring(0, 100),
          issue: 'Slow query with WHERE clause',
          suggestion: 'Consider adding indexes on columns used in WHERE clause',
          impact: 'high',
        });
      }

      // Check for JOIN performance
      if (query.includes('JOIN') && performance.executionTime > 2000) {
        suggestions.push({
          query: query.substring(0, 100),
          issue: 'Slow JOIN operation',
          suggestion: 'Review JOIN conditions and ensure proper indexes exist',
          impact: 'high',
        });
      }

      // Check for subqueries
      if (query.includes('SELECT') && query.includes('(SELECT')) {
        suggestions.push({
          query: query.substring(0, 100),
          issue: 'Query contains subqueries',
          suggestion:
            'Consider using JOINs instead of subqueries for better performance',
          impact: 'medium',
        });
      }

      // Check for LIKE with leading wildcard
      if (query.match(/LIKE\s+['"]%/)) {
        suggestions.push({
          query: query.substring(0, 100),
          issue: 'LIKE query with leading wildcard',
          suggestion:
            'Leading wildcards prevent index usage. Consider full-text search',
          impact: 'high',
        });
      }
    }

    // MongoDB-specific suggestions
    if (query.startsWith('{') || query.startsWith('[')) {
      try {
        const parsed = JSON.parse(query);

        // Check for missing indexes
        if (performance.executionTime > 1000) {
          suggestions.push({
            query: query.substring(0, 100),
            issue: 'Slow MongoDB query',
            suggestion: 'Consider adding indexes on frequently queried fields',
            impact: 'high',
          });
        }

        // Check for $regex usage
        if (JSON.stringify(parsed).includes('$regex')) {
          suggestions.push({
            query: query.substring(0, 100),
            issue: 'Using $regex in query',
            suggestion:
              'Consider using text indexes for better text search performance',
            impact: 'medium',
          });
        }

        // Check for large $in arrays
        if (
          JSON.stringify(parsed).includes('$in') &&
          performance.executionTime > 500
        ) {
          suggestions.push({
            query: query.substring(0, 100),
            issue: 'Large $in array in query',
            suggestion:
              'Consider breaking large $in queries into smaller batches',
            impact: 'medium',
          });
        }
      } catch {
        // Not a valid JSON query
      }
    }

    // General suggestions
    if (performance.executionTime > PERFORMANCE_THRESHOLDS.VERY_SLOW_QUERY_MS) {
      suggestions.push({
        query: query.substring(0, 100),
        issue: 'Very slow query execution',
        suggestion: 'Consider query optimization, caching, or database scaling',
        impact: 'high',
      });
    }

    if (!performance.cached && performance.executionTime > 500) {
      suggestions.push({
        query: query.substring(0, 100),
        issue: 'Frequently executed slow query',
        suggestion: 'Consider implementing query result caching',
        impact: 'medium',
      });
    }

    return suggestions;
  }

  /**
   * Periodic analysis of overall performance across all connections.
   *
   * Logs a summary per connection (total queries, average time, slow-query
   * ratio, cache-hit ratio) and warns about high slow-query ratios or
   * the top 5 slowest query patterns.
   */
  private analyzePerformance(): void {
    for (const [connection, stats] of this.statistics) {
      if (stats.totalQueries === 0) {
        continue;
      }

      const slowQueryRatio = stats.slowQueries / stats.totalQueries;
      const cacheHitRatio = stats.cachedQueries / stats.totalQueries;

      // Log performance summary
      this.logger.log(`Performance summary for ${connection}:`, {
        totalQueries: stats.totalQueries,
        averageExecutionTime: Math.round(stats.averageExecutionTime),
        slowQueries: stats.slowQueries,
        slowQueryRatio: (slowQueryRatio * 100).toFixed(2) + '%',
        cacheHitRatio: (cacheHitRatio * 100).toFixed(2) + '%',
      });

      // Alert on high slow query ratio
      if (slowQueryRatio > 0.1) {
        this.logger.warn(
          `High slow query ratio detected for ${connection}: ${(
            slowQueryRatio * 100
          ).toFixed(2)}%`,
        );
      }

      // Identify problematic query patterns
      const problematicPatterns = Array.from(stats.queryPatterns.values())
        .filter((p) => p.averageTime > PERFORMANCE_THRESHOLDS.SLOW_QUERY_MS)
        .sort((a, b) => b.averageTime - a.averageTime)
        .slice(0, 5);

      if (problematicPatterns.length > 0) {
        this.logger.warn(
          `Top slow query patterns for ${connection}:`,
          problematicPatterns.map((p) => ({
            pattern: p.pattern.substring(0, 100),
            count: p.count,
            averageTime: Math.round(p.averageTime),
          })),
        );
      }
    }
  }

  /**
   * Retrieve aggregated query statistics.
   *
   * @param connectionName - If provided, returns stats for that connection
   *   only. Otherwise returns a `Map` of all connections.
   * @returns A single {@link QueryStatistics} or a `Map<string, QueryStatistics>`.
   */
  getStatistics(
    connectionName?: string,
  ): QueryStatistics | Map<string, QueryStatistics> {
    if (connectionName) {
      return (
        this.statistics.get(connectionName) || this.createEmptyStatistics()
      );
    }
    return new Map(this.statistics);
  }

  /**
   * Retrieve generated optimisation suggestions.
   *
   * @param connectionName - If provided, returns suggestions for that
   *   connection only. Otherwise returns all suggestions across connections.
   * @returns Array of {@link OptimizationSuggestion} objects.
   */
  getOptimizationSuggestions(
    connectionName?: string,
  ): OptimizationSuggestion[] {
    if (connectionName) {
      return this.optimizationSuggestions.get(connectionName) || [];
    }

    const allSuggestions: OptimizationSuggestion[] = [];
    for (const suggestions of this.optimizationSuggestions.values()) {
      allSuggestions.push(...suggestions);
    }
    return allSuggestions;
  }

  /**
   * Retrieve recent query history entries.
   *
   * @param limit - Maximum number of entries to return (default `100`).
   * @param connectionName - Optional connection filter.
   * @returns Array of the most recent {@link QueryPerformance} entries.
   */
  getQueryHistory(limit = 100, connectionName?: string): QueryPerformance[] {
    let history = this.queryHistory;

    if (connectionName) {
      history = history.filter((q) => q.connection === connectionName);
    }

    return history.slice(-limit);
  }

  /**
   * Clear all statistics, query history, and optimisation suggestions.
   */
  clearStatistics(): void {
    this.statistics.clear();
    this.queryHistory.length = 0;
    this.optimizationSuggestions.clear();
    this.logger.log('Query statistics cleared');
  }

  /**
   * Export a comprehensive performance report.
   *
   * Includes per-connection statistics (with query patterns flattened to
   * arrays), the last 100 optimisation suggestions, and the top 10
   * slowest queries per connection.
   *
   * @returns A structured report suitable for dashboards or alerting.
   */
  exportPerformanceReport(): {
    timestamp: Date;
    connections: Array<{
      name: string;
      statistics: Omit<QueryStatistics, 'queryPatterns'> & {
        queryPatterns: QueryPatternStats[];
      };
      suggestions: OptimizationSuggestion[];
      topSlowQueries: QueryPerformance[];
    }>;
  } {
    const report: ReturnType<
      QueryOptimizationService['exportPerformanceReport']
    > = {
      timestamp: new Date(),
      connections: [],
    };

    for (const [connection, stats] of this.statistics) {
      const suggestions = this.optimizationSuggestions.get(connection) || [];
      const slowQueries = this.queryHistory
        .filter((q) => q.connection === connection && q.slow)
        .sort((a, b) => b.executionTime - a.executionTime)
        .slice(0, 10);

      report.connections.push({
        name: connection,
        statistics: {
          ...stats,
          queryPatterns: Array.from(stats.queryPatterns.values()),
        },
        suggestions,
        topSlowQueries: slowQueries,
      });
    }

    return report;
  }
}
